version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mindup-backend
    ports:
      - "8761:8761"  # Puerto de Eureka
      - "8080:8080"  # Puerto de Gateway
      - "8081:8081"  # Puerto de Chat
      - "8082:8082"  # Puerto de Core
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - mindup-network
    depends_on:
      - mongo
      - postgres
    volumes:
      - mindup-backend-data:/data

  # MongoDB (Base de datos no relacional)
  mongo:
    image: mongo:latest
    container_name: mindup-mongo
    ports:
      - "27017:27017"
    networks:
      - mindup-network
    volumes:
      - mindup-mongo-data:/data/db

  # PostgreSQL (Base de datos relacional)
  postgres:
    image: postgres:latest
    container_name: mindup-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mindupdb
    ports:
      - "5432:5432"
    networks:
      - mindup-network
    volumes:
      - mindup-postgres-data:/var/lib/postgresql/data

networks:
  mindup-network:
    driver: bridge

volumes:
  mindup-mongo-data:
    driver: local
  mindup-postgres-data:
    driver: local
  mindup-backend-data:
    driver: local
